"""tests/test_mcp_server.py
=========================
Unit tests for the Sentinel MCP server wrapper.

Scope
-----
The MCP server uses asyncio + stdio. Full integration testing requires
spinning up a stdio loop and a paired client, which is heavy and brittle
in CI. These tests focus on what can be verified deterministically and
without network/stdio:

1. ``_build_server`` returns a configured ``mcp.server.Server`` for a
   valid workspace.
2. ``_build_server`` raises ``FileNotFoundError`` for a missing workspace.
3. ``_build_server`` rejects path-traversal workspace names (delegated
   to :class:`FactoryDataManager`'s constructor validation).
4. The data manager is registered as the tool-registry singleton after
   ``_build_server`` runs (verifies the wrapper is wired up correctly).

End-to-end MCP transport integration tests are deferred to a Phase 5+
manual run with Claude Desktop.

Workspace patching note
-----------------------
``WORKSPACES_DIR`` is a module-level constant referenced from THREE
places: :mod:`src.core.config`, :mod:`src.core.state_manager` (which
imports it directly), and :mod:`src.mcp_server.server` (which also
imports it directly). Each direct import binds its own name, so we
monkeypatch all three to point the test at a temporary directory.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Ensure the project root is on sys.path so ``src`` resolves when pytest
# is invoked from any working directory. Mirrors the pattern already used
# in tests/test_edge_cases.py.
_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

import pandas as pd
import pytest


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def temp_workspaces_root(tmp_path, monkeypatch):
    """Redirect WORKSPACES_DIR to a temp directory across all import sites.

    Returns the (now-redirected) workspaces root Path. Tests can create
    workspace subdirectories under this root and they will be found by
    ``_build_server``.
    """
    ws_root = tmp_path / "workspaces"
    ws_root.mkdir(parents=True)

    # Patch the constant at every import site that has already cached it.
    monkeypatch.setattr("src.core.config.WORKSPACES_DIR", ws_root)
    monkeypatch.setattr("src.core.state_manager.WORKSPACES_DIR", ws_root)
    monkeypatch.setattr("src.mcp_server.server.WORKSPACES_DIR", ws_root)

    return ws_root


@pytest.fixture
def populated_workspace(temp_workspaces_root) -> str:
    """Create a minimal workspace on disk and return its name.

    Writes a small inventory CSV. The transaction log and trust scores
    are auto-generated by :class:`FactoryDataManager` on first access,
    so we don't need to seed them here.
    """
    ws_name = "test_ws"
    ws_dir: Path = temp_workspaces_root / ws_name
    ws_dir.mkdir()

    inventory = pd.DataFrame(
        [
            {
                "item_id": "ITEM-A",
                "current_stock": 100,
                "max_capacity": 500,
                "unit_cost_usd": 1.0,
            },
            {
                "item_id": "ITEM-B",
                "current_stock": 50,
                "max_capacity": 200,
                "unit_cost_usd": 2.5,
            },
        ]
    )
    inventory.to_csv(ws_dir / "inventory.csv", index=False)
    return ws_name


@pytest.fixture(autouse=True)
def reset_tool_data_manager():
    """Clear the tool registry's data manager singleton between tests.

    ``set_data_manager`` is a process-wide mutation; without resetting
    we'd leak state into subsequent tests (e.g. one test's
    FactoryDataManager pointing at a tmp dir that has been removed).
    """
    yield
    from src.tools import tool_registry

    tool_registry._data_manager = None


# ---------------------------------------------------------------------------
# Tests — _build_server
# ---------------------------------------------------------------------------


def test_build_server_returns_configured_server(populated_workspace):
    """Happy path: an existing workspace yields a usable Server object."""
    from mcp.server import Server as MCPServer

    from src.mcp_server.server import _build_server

    server = _build_server(populated_workspace)

    assert server is not None
    assert isinstance(server, MCPServer)
    # The Server is named 'sentinel-mcp' so MCP clients can identify it.
    assert server.name == "sentinel-mcp"


def test_build_server_unknown_workspace_raises(temp_workspaces_root):
    """A non-existent workspace name produces a FileNotFoundError."""
    from src.mcp_server.server import _build_server

    with pytest.raises(FileNotFoundError) as excinfo:
        _build_server("does_not_exist")

    assert "Workspace not found" in str(excinfo.value)


def test_build_server_rejects_path_traversal(temp_workspaces_root):
    """Path-traversal workspace names are rejected by the data manager.

    The FactoryDataManager constructor raises ValueError on any name
    containing ``..``, ``/``, or ``\\``. Verify the MCP server does not
    bypass that check.
    """
    from src.mcp_server.server import _build_server

    # Create a directory that LOOKS like the resolved target so the
    # FileNotFoundError doesn't fire first — we want to confirm the
    # ValueError from FactoryDataManager wins. With ".." in the name,
    # WORKSPACES_DIR / ".." resolves to tmp_path itself, which exists.
    with pytest.raises(ValueError) as excinfo:
        _build_server("..")
    assert "Invalid workspace name" in str(excinfo.value)


def test_build_server_registers_data_manager_singleton(populated_workspace):
    """After _build_server, the tool registry's singleton points at the new manager."""
    from src.mcp_server.server import _build_server
    from src.tools.tool_registry import get_data_manager

    server = _build_server(populated_workspace)
    assert server is not None

    dm = get_data_manager()
    assert dm.workspace == populated_workspace


def test_build_server_inventory_loads(populated_workspace):
    """Confirm the seeded inventory is reachable via the data manager.

    This catches the failure mode where _build_server points at the
    wrong directory (e.g. ``WORKSPACES_DIR`` not patched at every site)
    and silently auto-generates mock data instead of loading the
    workspace we created.
    """
    from src.mcp_server.server import _build_server
    from src.tools.tool_registry import get_data_manager

    _build_server(populated_workspace)
    df = get_data_manager().get_inventory()

    assert "item_id" in df.columns
    assert set(df["item_id"]) == {"ITEM-A", "ITEM-B"}


# ---------------------------------------------------------------------------
# Tests — module imports
# ---------------------------------------------------------------------------


def test_package_exports():
    """The package re-exports the public surface."""
    import src.mcp_server as pkg

    assert hasattr(pkg, "run_server")
    assert hasattr(pkg, "_build_server")
    assert "run_server" in pkg.__all__
    assert "_build_server" in pkg.__all__


def test_main_module_importable():
    """``python -m src.mcp_server`` entrypoint is importable."""
    import src.mcp_server.__main__ as entry

    assert callable(entry.main)
